# Generated by Django 4.2.27 on 2026-02-01 18:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='User', max_length=255)),
                ('file', models.FileField(help_text='Upload resume in PDF, DOCX, or TXT format', upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt'])])),
                ('content', models.TextField(blank=True, help_text='Extracted text from resume')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Current active resume')),
            ],
            options={
                'verbose_name': 'User Resume',
                'verbose_name_plural': 'User Resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_url', models.URLField(help_text='URL of the job description', max_length=1000)),
                ('job_description', models.TextField(blank=True, help_text='Extracted job description')),
                ('additional_instructions', models.TextField(blank=True, help_text='Additional instructions for AI to customize resume/cover letter')),
                ('generate_resume', models.BooleanField(default=True, help_text='Generate/Update resume')),
                ('generate_cover_letter', models.BooleanField(default=True, help_text='Generate cover letter')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='resume_generator.userresume')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Generated resume content')),
                ('recommendations', models.TextField(blank=True, help_text='AI recommendations for improving the resume')),
                ('file_path', models.CharField(blank=True, help_text='Path to generated file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_resumes', to='resume_generator.jobapplication')),
            ],
            options={
                'verbose_name': 'Generated Resume',
                'verbose_name_plural': 'Generated Resumes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Generated cover letter content')),
                ('file_path', models.CharField(blank=True, help_text='Path to generated file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_cover_letters', to='resume_generator.jobapplication')),
            ],
            options={
                'verbose_name': 'Generated Cover Letter',
                'verbose_name_plural': 'Generated Cover Letters',
                'ordering': ['-created_at'],
            },
        ),
    ]
