# Generated by Django 4.2.27 on 2026-02-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFileTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to Excel file', max_length=500, unique=True)),
                ('is_monitoring', models.BooleanField(default=False, help_text='Is currently being monitored')),
                ('last_checked', models.DateTimeField(blank=True, help_text='Last time file was checked', null=True)),
                ('last_modified', models.DateTimeField(blank=True, help_text='Last modification time of file', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Excel File Tracker',
                'verbose_name_plural': 'Excel File Trackers',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_generated',
            field=models.BooleanField(default=False, help_text='Cover letter has been generated'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='excel_row_index',
            field=models.IntegerField(blank=True, help_text='Row index in Excel file', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='generate_new_resume',
            field=models.BooleanField(default=True, help_text='If False, only generate cover letter and recommendations without updating resume'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume_generated',
            field=models.BooleanField(default=False, help_text='Resume has been generated'),
        ),
    ]
