# Generated by Django 4.2.27 on 2026-02-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0002_excelfiletracker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file_id', models.CharField(help_text='Google Drive File ID for Excel file', max_length=500)),
                ('excel_file_name', models.CharField(blank=True, help_text='Excel file name', max_length=500)),
                ('output_folder_id', models.CharField(help_text='Google Drive Folder ID for output docs', max_length=500)),
                ('is_monitoring', models.BooleanField(default=False, help_text='Is currently being monitored')),
                ('last_checked', models.DateTimeField(blank=True, help_text='Last time file was checked', null=True)),
                ('last_modified', models.DateTimeField(blank=True, help_text='Last modification time of file', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Drive Config',
                'verbose_name_plural': 'Google Drive Configs',
            },
        ),
        migrations.DeleteModel(
            name='ExcelFileTracker',
        ),
        migrations.AddField(
            model_name='generatedcoverletter',
            name='google_doc_id',
            field=models.CharField(blank=True, help_text='Google Docs ID', max_length=500),
        ),
        migrations.AddField(
            model_name='generatedcoverletter',
            name='google_doc_url',
            field=models.URLField(blank=True, help_text='Google Docs URL', max_length=1000),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='company_name',
            field=models.CharField(blank=True, help_text='Extracted company name', max_length=500),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='google_doc_id',
            field=models.CharField(blank=True, help_text='Google Docs ID (combined doc with cover letter)', max_length=500),
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='google_doc_url',
            field=models.URLField(blank=True, help_text='Google Docs URL', max_length=1000),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='company_name',
            field=models.CharField(blank=True, help_text='Extracted company name', max_length=500),
        ),
    ]
