# Generated by Django 4.2.27 on 2026-02-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0003_googledriveconfig_delete_excelfiletracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledriveconfig',
            name='always_generate_cover_letter',
            field=models.BooleanField(default=True, help_text='Always generate cover letter regardless of resume setting'),
        ),
        migrations.AddField(
            model_name='googledriveconfig',
            name='generate_new_resume',
            field=models.BooleanField(default=True, help_text='Generate new tailored resume for each job (requires uploaded resume)'),
        ),
        migrations.AddField(
            model_name='googledriveconfig',
            name='generate_recommendations',
            field=models.BooleanField(default=True, help_text='Generate AI recommendations for resume improvement'),
        ),
    ]
