# Generated by Django 4.2.27 on 2026-02-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0004_googledriveconfig_always_generate_cover_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_description',
            field=models.TextField(blank=True, help_text='Job description text (required if job_url is empty)'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_url',
            field=models.URLField(blank=True, help_text='URL of the job description (optional if job_description is provided)', max_length=1000),
        ),
    ]
