# Generated by Django 4.2.27 on 2026-02-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0005_alter_jobapplication_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='unique_id',
            field=models.CharField(blank=True, help_text='Unique identifier for Excel row sync', max_length=100, unique=True),
        ),
    ]
