# Generated by Django 4.2.27 on 2026-02-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_generator', '0006_jobapplication_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledriveconfig',
            name='auto_cleanup_old_jobs',
            field=models.BooleanField(default=False, help_text='Automatically archive jobs not found in Excel during sync'),
        ),
    ]
